### ISSUE TITLE
Use JSON for meta data

### ISSUE THREAD

**Issue by ewels** [nf-core/modules#11]
The more I think about it, the more I think that JSON is more appropriate for the meta information. We have nested lists and other semi-complicated structures at JSON is more verbose and clear with this stuff.

**Comment by grst** [comment]
I thought JSON is a bit out-of-fashion nowadays in favor of YAML/TOML as it's harder to read/write for human beings. 

Is there no way of simplifying the config file instead? For instance, why can't this 
```yaml
input:
    -
        - input:
            type: file
            description: Input BAM or CRAM file
            pattern: *.{bam,cram}
```

just be that?
```yaml
input:
        - input:
            type: file
            description: Input BAM or CRAM file
            pattern: *.{bam,cram}
```

(or in TOML)
```toml
[input]
  [input]
  type="file"
  description="Input BAM"
  pattern="*.{bam,cream"
```
