### ISSUE TITLE
new module: damageprofiler

### ISSUE THREAD

**Issue by maxibor** [nf-core/modules#285]
https://github.com/Integrative-Transcriptomics/DamageProfiler

Typical usage:
```
damageprofiler -i bam_file -r reference_fasta -o output_directory
```

Already used in nf-core pipelines such as [Eager](https://nf-co.re/eager), and [coproID](https://nf-co.re/coproid)

**Comment by maxibor** [comment]
Issue of running a bioconda package with biocontainer (docker container).
The (java) package works fine when using it with conda, but fails with
```
Caused by: java.lang.NullPointerException
    at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
```
when used through docker.

Looks like the solution is updating the conda package with `libfontconfig1` https://github.com/AdoptOpenJDK/openjdk-docker/issues/75

The bioconda package is https://bioconda.github.io/recipes/damageprofiler/README.html?highlight=damageprofiler#package-package%20'damageprofiler&#x27;

**Comment by grst** [comment]
updating the conda package sounds good! You can request a review from me, then we can get it in quickly.

**Comment by maxibor** [comment]
After addding the [fontconfig](https://anaconda.org/anaconda/fontconfig) package to the DamageProfiler recipe and rebuilding the conda package, and the biocontainer with [mulled-build](https://galaxy-lib.readthedocs.io/en/latest/topics/mulled.html#building-docker-containers-for-local-conda-packages) this doesn't solve the issue.
I'm afraid that this actually needs to modifiy the Dockerfile (according to AdoptOpenJDK/openjdk-docker#75)

**Comment by maxibor** [comment]
Also tried with extended bioconda base-image, but still no luck. See recipe below

```
{% set version = "1.1" %}
{% set sha256 = "009a5d6a638f73ef9b7f9e3cf0182e184a176d8b9e9344d33a850f2b7945a126" %}


package:
  name: damageprofiler
  version: '{{version}}'

source:
  url: https://github.com/Integrative-Transcriptomics/DamageProfiler/releases/download/v{{ version }}/DamageProfiler-{{ version }}-java11.jar
  sha256: '{{sha256}}'

build:
  noarch: generic
  number: 1

extra:
  container:
    extended-base: True

requirements:
  run:
    - openjdk >=11
    - python
    - fontconfig

test:
  commands:
    - damageprofiler -h

about:
  home: https://github.com/Integrative-Transcriptomics/DamageProfiler
  license: GPL-3.0
  license_family: GPL
  summary: A Java based tool to determine damage patterns on ancient DNA as a replacement for mapDamage

```
