### ISSUE TITLE
Upload on failure not naming artifact correctly 

### ISSUE THREAD

**Issue by adamrtalbot** [nf-core/modules#3492]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

After failure, logs are being uploaded as artifact `logs-${{ profile }}-`. Looking at line the [following line](https://github.com/nf-core/modules/blob/6a24fbe314bb2e6fe6306c29a63076ea87e8eb3c/.github/workflows/pytest-workflow.yml#L245), it's trying to use a variable that doesn't exist:

```
name: logs-${{ matrix.profile }}-${{ steps.parsed.outputs.result }}
```

Here's is `step: parsed` which must not be setting the output correctly:
```
      - name: Setting global variables
        uses: actions/github-script@v6
        id: parsed
        with:
          script: |
            return '${{ matrix.tags }}'.toLowerCase().replaceAll(/\//g, '-').trim('-').trim('"')
          result-encoding: string
 ```

Inside the zip, files are named `pytest_workflow_${{ hash }}_` which is also missing the final element but I'm not sure why this is.

### Command used and terminal output

```console
N/A
```

### Relevant files

N/A

### System information

N/A
