### ISSUE TITLE
new module: ASHLAR

### ISSUE THREAD

**Issue by RobJY** [nf-core/modules#3550]
### Is there an existing module for this?

- [X] I have searched for the existing module

### Is there an open PR for this?

- [X] I have searched for existing PRs

### Is there an open issue for this?

- [X] I have searched for existing issues

### Are you going to work on this?

- [X] If I'm planning to work on this module, I added myself to the `Assignees` to facilitate tracking who is working on the module

**Comment by RobJY** [comment]
I'm unable to add myself as an Assignee, but am working on this issue.

Where should I request permission to set that?  the modules channel in Slack?

**Comment by RobJY** [comment]
Here's the top of our meta.yml to give some background on the module:
```
name: "ashlar"
description: Alignment by Simultaneous Harmonization of Layer/Adjacency Registration
keywords:
  - image_processing
  - alignment
  - registration
tools:
  - "ashlar":
      description: "Alignment by Simultaneous Harmonization of Layer/Adjacency Registration"
      homepage: "https://labsyspharm.github.io/ashlar/"
      documentation: "https://labsyspharm.github.io/ashlar/"
      doi: "10.1093/bioinformatics/btac544"
      licence: ["MIT"]
```
