### ISSUE TITLE
CI fails if matrix is larger than 256

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/modules#391]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix

**Comment by junaruga** [comment]
I am curious where is the repository using CI which the number of cases in the matrix is larger than 256?

**Comment by Emiller88** [comment]
@junaruga https://github.com/nf-core/modules/pull/389 See here

**Comment by junaruga** [comment]
@Emiller88 thanks. I can see the pull-request's number of checks (cases) is 12, not larger (bigger) than 256. I can not find a number more than 256 there. What the 256 actually mean?
https://github.com/nf-core/modules/pull/389/checks

**Comment by ewels** [comment]
This could be useful: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations

```yaml
runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [macos-latest, windows-latest, ubuntu-18.04]
    node: [8, 10, 12, 14]
    include:
      # includes a new variable of npm with a value of 6
      # for the matrix leg matching the os and version
      - os: windows-latest
        node: 8
        npm: 6
```

So basically you make a "thin" minimal matrix of combinations and then inject in one or two additional use cases. For example, you could run a matrix of tags with a single version of nextflow and just docker, then have a single tag / test running for different versions of Nextflow / Singularity / Conda.

I have written a workflow like this myself somewhere, but I have no idea where and I can't find it now. But the syntax is not too difficult.

**Comment by ewels** [comment]
Example from @maxulysse: https://github.com/nf-core/sarek/blob/68b9930a74962f3c42eee71f51e6dd2646269199/.github/workflows/ci.yml#L173-L189

```yml
  tools:
    env:
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [Haplotypecaller, Freebayes, Manta, mpileup, MSIsensor, Strelka, TIDDIT]
        intervals: [--no_intervals, '']
        exclude:
          - tool: Manta
            intervals: --no_intervals
          - tool: MSIsensor
            intervals: --no_intervals
          - tool: Strelka
            intervals: --no_intervals
          - tool: TIDDIT
            intervals: --no_intervals
```
