### ISSUE TITLE
Fix `meta.yml` structure for input and output tuples

### ISSUE THREAD

**Issue by ewels** [nf-core/modules#4983]
The current contents of the `meta.yml` files does not correspond to the actual processes in most modules. This limits how useful these metadata files can be.

For example, consider `abacas`. The `meta.yml` file shows 3 inputs:

https://github.com/nf-core/modules/blob/53a97948affb07725328a1bba2fec79b331374a6/modules/nf-core/abacas/meta.yml#L17-L30

However, there are only 2 inputs in `main.nf` (the first one being a tuple with two elements):

https://github.com/nf-core/modules/blob/53a97948affb07725328a1bba2fec79b331374a6/modules/nf-core/abacas/main.nf#L10-L12

The correct YAML structure to describe this should be:

```yaml

 input: 
   -
       - meta: 
           type: map 
           description: | 
             Groovy Map containing sample information 
             e.g. [ id:'test', single_end:false ] 
       - scaffold: 
           type: file 
           description: Fasta file containing scaffold 
           pattern: "*.{fasta,fa}" 
   - fasta: 
       type: file 
       description: FASTA reference file 
       pattern: "*.{fasta,fa}" 
```

The difference is pretty difficult to see in YAML (\*cough\* see https://github.com/nf-core/modules/issues/11 \*cough\*), but now we have two inputs. The first is an array containing two elements.

This error seems to be present in basically any modules containing a tuple, as all `meta.yml` files seems to have a flat array of inputs.

We should be doing better automation of this file from nf-core/tools in order to solve this problem. I started a brief proof of concept on how we can do this in https://github.com/nf-core/tools/pull/2789 and described a rough outline of what needs doing.

**Comment by nvnieuwk** [comment]
I fully agree with this! Maybe using `[]` instead of `-` for arrays will make this a bit more clear to read?

**Comment by nvnieuwk** [comment]
Although I'm not sure it's possible to create multiline lists that way

**Comment by nvnieuwk** [comment]
https://www.w3schools.io/file/yaml-multiline-arrays/

**Comment by mashehu** [comment]
tbh: also quite easy to overlook what is inside the array in json:
```json
{
  "input": [
    [
      {
        "meta": {
          "type": "map",
          "description": "Groovy Map containing sample information \ne.g. [ id:'test', single_end:false ] \n"
        }
      },
      {
        "scaffold": {
          "type": "file",
          "description": "Fasta file containing scaffold",
          "pattern": "*.{fasta,fa}"
        }
      }
    ],
    {
      "fasta": {
        "type": "file",
        "description": "FASTA reference file",
        "pattern": "*.{fasta,fa}"
      }
    }
  ]
}
```
how about adding comment, so it is not just one lonely dash, helping to distinguish things:
```yaml
 input: 
   - #input tuple
       - meta: 
           type: map 
           description: | 
             Groovy Map containing sample information 
             e.g. [ id:'test', single_end:false ] 
       - scaffold: 
           type: file 
           description: Fasta file containing scaffold 
           pattern: "*.{fasta,fa}" 
   - fasta: 
       type: file 
       description: FASTA reference file 
       pattern: "*.{fasta,fa}" 
```
