### ISSUE TITLE
`samtools_sort` fasta is not optional

### ISSUE THREAD

**Issue by eperezme** [nf-core/modules#6220]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

When I was runing a workflow, samtools_sort used to take only the `.bam` files as an imput. At some point it was updated and the input of `SAMTOOLS_SORT` was:
```nf
    input:
    tuple val(meta) , path(bam)
    tuple val(meta2), path(fasta)
```

Technically the `meta.yml` says that the `fasta`  is optional:
```yml
  - fasta:
      type: file
      description: Reference genome FASTA file
      pattern: "*.{fa,fasta,fna}"
      optional: true
```

But on my workflow when I call the function with only one input value, an error is raised.

### Command used and terminal output

```console
SAMTOOLS_SORT_ALIGNED (
    BISMARK_ALIGN.out.bam,
)

Process `NFCORE_METHYLATION:METHYLATION:BISMARK:SAMTOOLS_SORT` declares 2 input channels but 1 were specified
```
